version: "3.8"
services:
  web:
    # Build the custom image from the Dockerfile in the current directory
    # build:
    #   context: .
    #   dockerfile: Dockerfile  # Optional, if the Dockerfile is named "Dockerfile"

    # Set a custom image name
    image: nginx:alpine # This is the image name

    # Set a custom container name
    container_name: virlab # This is the container name

    # Expose port 80 in the container to port 8080 on the host machine
    ports:
      - "8080:80"

    # Mount the local ./frontend directory to the container
    volumes:
      - ./frontend:/usr/share/nginx/html:Z
      - ./nginx.conf:/etc/nginx/nginx.conf:Z

    user: root

    # Optional: Environment variables
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

# version: '3'
# services:
#   web:
#     image: nginx:alpine
#     container_name: virlab
#     volumes:
#       - ./frontend:/usr/share/nginx/html
#       - ./nginx.conf:/etc/nginx/nginx.conf
#     user: root  # <-- Add this line
#     ports:
#       - "8080:80"
